[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci --include=dev --include=optional --include-workspace-root --ignore-scripts"
]

[variables]
NPM_CONFIG_INCLUDE = "optional"

[phases.build]
cmds = [
  "node apps/web/scripts/ensure-native-css-bindings.cjs",
  "npm run build --workspace=web",
]

[start]
cmd = "npm run start --workspace=web"
